apiVersion: v1
kind: ConfigMap
metadata:
  name: injector-mesh
  namespace: istio-control
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: trafficdirector.googleapis.com:443

      # Envoy proxy port to listen on for the admin interface. Envoy's admin page
      # is only accessible at the specified port locally. This port must be
      # different from PROXY_STATS_PORT when both are set. Default to 15000 when
      # not set. Port values lower or equaled to 1024 are not supported.
      # The following ports are reserved and should NOT be used:
      #   * 15001
      #   * 15006
      proxyAdminPort: 15000

      proxyMetadata:
        # GCP Project number where Traffic Director resources are configured.
        # This is a numeric identifier of your project (e.g. "111222333444").
        # You can get a list of all your projects with their corresponding numbers by
        # using "gcloud projects list" command or looking it up under "Project info"
        # section of your GCP console.
        # If left empty, configuration will be attempted to be fetched for the GCP
        # project associated with service credentials.
        # Leaving empty is not recommended as it is not guaranteed to work in future
        # releases.
        TRAFFICDIRECTOR_GCP_PROJECT_NUMBER: "360959748434"

        # GCP VPC network name for which the configuration is requested (This is the VPC
        # network name referenced in the forwarding rule in GCP API). If left empty,
        # configuration will be attempted to be fetched for the VPC network over which
        # the request to Traffic Director (trafficdirector.googleapis.com) is sent out.
        # Leaving empty is not recommended as it is not guaranteed to work in future
        # releases.
        TRAFFICDIRECTOR_NETWORK_NAME: "playground-k8s-vpc"

        # The port at which Envoy's /stats page can be accessed externally(from any source).
        # This setting is independent of the setting "proxyAdminPort". When both are set,
        # they must be different. When this port is not set, Envoy's admin interface can
        # only be accessed from localhost.
        #
        # Port values lower or equaled to 1024 are not supported. The following ports are
        # reserved and should NOT be used:
        #   * 15000
        #   * 15001
        #   * 15006
        # PROXY_STATS_PORT: "16000"
---
